'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("rotroRacer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_arena_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_arena_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_choose_racer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_choose_racer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_choose_racer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_choose_racer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_details() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_details", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_left_arrow2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_left_arrow2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_left_arrow3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_left_arrow3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_options1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_options1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_selection_menu_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_selection_menu_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_selection_menu_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_selection_menu_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_ship_selection_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_ship_selection_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_ship_selection_title_55pt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_ship_selection_title_55pt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_ship_selection_title_60pt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_ship_selection_title_60pt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_ship_selection_title_65pt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_ship_selection_title_65pt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_space_shuttle6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_space_shuttle6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_start_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_start_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rotro_racer_start_image2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rotro_racer_start_image2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property space_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("space-03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
